Add LDAPVerifyServerCert directive
dariko/httpd-rproxy-ldap pull request #3
Opened 2017-03-06 04:51 UTC by deecay

This PR adds control over LDAPVerifyServerCert.

2017-03-06 08:37 UTC, dariko requested changes
Looks good. I left an inline comment that should be worked out before merging.
Thanks

2017-03-06 08:37 UTC, dariko commented on proxy_ldap.conf.template
> +$([[ -v NO_VERIFY_SERVER_CERT ]] && { echo "
I think this block should be placed after the `LoadModule ldap_module` line , possibly just before the
```
$([[ -v LDAPS_CACERT_PEM ]] && { echo "
```

2017-03-06 08:57 UTC, deecay commented on proxy_ldap.conf.template
> +$([[ -v NO_VERIFY_SERVER_CERT ]] && { echo "
Changed.

2018-04-19 12:55 UTC, dariko approved these changes

2018-04-19 12:55 UTC, merged

2018-04-19 12:56 UTC, dariko commented
thank you!